### ISSUE TITLE
Error when getting Coupons

### ISSUE THREAD

**Issue by nils2525** [Staubteufel/AliCouponHunter#2]
2017-04-29 14:29:17,788| Get Coupons.
2017-04-29 14:29:20,859| (<type 'exceptions.AttributeError'>, AttributeError("'NoneType' object has no attribute 'a'",), <traceback object at 0x762df260>)

**Comment by Tadelsucht** [comment]
That can sometimes happen if the shops have edit their front page on an unsual way. By default the script would stop after 100 of those exceptions (STOP_CONSECUTIVELY_ERROR_NUMBER = 100).

**Comment by Tadelsucht** [comment]
Ok.. Maybe they changed the default shop page. I will check this.

**Comment by Tadelsucht** [comment]
Aliexpress has started to force the bot early to login. Maybe a increased "SLEEP_TIME" will help to avoid this.

**Comment by nils2525** [comment]
Can you implement a login feature or something similiar?

**Comment by Tadelsucht** [comment]
With following configuration it works. Slower but it works, and still fast enough for me👍 
SLEEP_TIME = 60
SLEEP_TIME_PLUS_MINUS = 30
